global:

route:
  receiver: 'slack-notifications'
receivers:
  - name: 'slack-notifications'
    slack_configs:
      - api_url: https://hooks.slack.com/services/changeme
        channel: '#shopping-api-dev-alerts'
        send_resolved: true # this option makes the alert-manager send another message on slack channel once the alert is resolved