global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - /etc/prometheus/rules/common/*.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
  - job_name: alertmanager
    static_configs:
      - targets:
          - alertmanager:9093
  - job_name: tempo
    static_configs:
      - targets:
          - tempo:3100
  - job_name: loki
    static_configs:
      - targets:
          - loki:3100
  #  - job_name: postgres-exporter
  #    static_configs:
  #      - targets:
  #        - postgres-exporter:9187
  - job_name: keycloak
    static_configs:
      - targets:
          - keycloak:8080
  - job_name: keycloak_shopping_api
    metrics_path: /realms/shopping-api/metrics
    static_configs:
      - targets:
          - keycloak:8080
  - job_name: service-discovery
    metrics_path: /private/metrics
    static_configs:
      - targets:
          - service-discovery:8081
  - job_name: gateway
    metrics_path: /private/metrics
    static_configs:
      - targets:
          - gateway:8080
  - job_name: sales-catalog
    metrics_path: /sales-catalog/private/metrics
    static_configs:
      - targets:
          - sales-catalog:8082