{
 "title": "Keycloak Realm",
 "tags": [
  "java",
  "keycloak",
  "quarkus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "groot-mg", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Keycloak response total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(keycloak_response_total) by (code, method, resource)",
     "legendFormat": "{{code}}-{{method}}-{{resource}}"
    }
   ]
  },
  {
   "title": "p99 Keycloak response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(keycloak_request_duration_bucket[1m])) by (code, method, resource, le))",
     "legendFormat": "{{code}}-{{method}}-{{resource}}"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory init",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "jvm_memory_bytes_init", "legendFormat": "{{area}}" }
     ]
    },
    {
     "title": "Memory max",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "jvm_memory_bytes_max", "legendFormat": "{{area}}" }
     ]
    },
    {
     "title": "Memory pool init",
     "type": "stat",
     "gridPos": { "h": 5, "w": 9, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "jvm_memory_pool_bytes_init", "legendFormat": "{{pool}}" }
     ]
    },
    {
     "title": "Memory pool max",
     "type": "stat",
     "gridPos": { "h": 5, "w": 9, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "jvm_memory_pool_bytes_max", "legendFormat": "{{pool}}" }
     ]
    },
    {
     "title": "Memory used",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "jvm_memory_bytes_used", "legendFormat": "{{area}}" }
     ]
    },
    {
     "title": "Memory commited",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "jvm_memory_bytes_committed", "legendFormat": "{{area}}" }
     ]
    },
    {
     "title": "Memory pool used",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "jvm_memory_pool_bytes_used", "legendFormat": "{{pool}}" }
     ]
    },
    {
     "title": "Memory pool commited",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_committed",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Virtual memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{job=\"keycloak_shopping_api\"}",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Memory pool allocated total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_allocated_bytes_total",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Thread count total",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "jvm_threads_current", "legendFormat": "total" }
     ]
    },
    {
     "title": "Thread daemon peak",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "jvm_threads_peak", "legendFormat": "total" }
     ]
    },
    {
     "title": "Threads deadlock monitor",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "jvm_threads_deadlocked_monitor", "legendFormat": "total" }
     ]
    },
    {
     "title": "Thread daemon total",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "jvm_threads_daemon", "legendFormat": "total" }
     ]
    },
    {
     "title": "Thread started total",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "jvm_threads_started_total", "legendFormat": "total" }
     ]
    },
    {
     "title": "Threads deadloc",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "jvm_threads_deadlocked", "legendFormat": "total" }
     ]
    },
    {
     "title": "Classes loaded",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "jvm_classes_loaded", "legendFormat": "total" }
     ]
    },
    {
     "title": "Classes unloaded",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "jvm_classes_unloaded_total", "legendFormat": "total" }
     ]
    },
    {
     "title": "GC collection time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "jvm_gc_collection_seconds_count",
       "legendFormat": "{{gc}}"
      }
     ]
    },
    {
     "title": "CPU Seconds total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "process_cpu_seconds_total{job=\"keycloak_shopping_api\"}",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "threads state",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "jvm_threads_state", "legendFormat": "{{state}}" }
     ]
    }
   ]
  }
 ]
}