{
 "title": "Springboot/Micrometer Dashboard",
 "description": "Dashboard for Spring Boot Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\"}, instance)"
    }
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\", area=\"heap\"},id)"
    }
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\", area=\"nonheap\"},id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basic Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_uptime_seconds{application=\"$application\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=~\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=~\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=~\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=~\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Process Open Files",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(process_files_open_files{application=\"$application\", instance=~\"$instance\"})",
     "legendFormat": "Open Files"
    },
    {
     "expr": "sum(process_files_max_files{application=\"$application\", instance=~\"$instance\"})",
     "legendFormat": "Max Files"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "avg(process_start_time_seconds{application=\"$application\", instance=~\"$instance\"})*1000"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"$application\", instance=~\"$instance\"} * 1000 / system_cpu_count{application=\"$application\", instance=~\"$instance\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{application=\"$application\", instance=~\"$instance\"} * 1000 / system_cpu_count{application=\"$application\", instance=~\"$instance\"}",
     "legendFormat": "JVM CPU Usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(system_load_average_1m{application=\"$application\", instance=~\"$instance\"})",
     "legendFormat": "Load Average [1m]"
    },
    {
     "expr": "sum(system_cpu_count{application=\"$application\", instance=~\"$instance\"})",
     "legendFormat": "CPU Core Size"
    }
   ]
  },
  {
   "title": "HTTP Server Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request rate (TPS)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=~\"$instance\", uri!=\"UNKNOWN\"}[1m])) by (method, status, uri)",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    },
    {
     "title": "Response duration",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{application=\"$application\",instance=~\"$instance\",uri!~\"UNKNOWN\"}[1m])) by (method,status,uri) / sum(rate(http_server_requests_seconds_count{application=\"$application\",instance=~\"$instance\", uri!~\"UNKNOWN\"}[1m])) by (method,status,uri)",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      },
      {
       "expr": "sum(max(http_server_requests_seconds_max{application=\"$application\", instance=~\"$instance\", uri!~\"UNKNOWN\"}))",
       "legendFormat": "HTTP - MAX"
      }
     ]
    },
    {
     "title": "Request Count (total)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(http_server_requests_seconds_count{application=\"$application\", instance=~\"$instance\", uri!=\"UNKNOWN\"}) by (method, status, uri)",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\",instance=~\"$instance\",uri!=\"UNKNOWN\",status=~\"5..\"}[1m])) by (method, status, uri)",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    },
    {
     "title": "Histogram (p90)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=~\"$instance\", uri!~\"UNKNOWN\"}[1m])) by (le, method, status, uri))",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    },
    {
     "title": "Histogram (p99)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=~\"$instance\",uri!~\"UNKNOWN\"}[1m])) by (le, method, status, uri))",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    },
    {
     "title": "Histogram (p50)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=~\"$instance\", uri!~\"UNKNOWN\"}[1m])) by (le, method, status, uri))",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Pools (heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "$memory_pool_heap (heap)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "repeat": "memory_pool_heap",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=~\"$instance\", id=\"$memory_pool_heap\"}) by (id)",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", instance=~\"$instance\", id=\"$memory_pool_heap\"}) by (id)",
       "legendFormat": "Commited"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instance=~\"$instance\", id=~\"$memory_pool_heap\"}) by (id)",
       "legendFormat": "Max - {{id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Pools (nonheap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "$memory_pool_nonheap (nonheap)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
     "repeat": "memory_pool_nonheap",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=~\"$instance\", id=~\"$memory_pool_nonheap\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", instance=~\"$instance\", id=~\"$memory_pool_nonheap\"})",
       "legendFormat": "Commited"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{application=\"$application\",instance=~\"$instance\",id=~\"$memory_pool_nonheap\"})",
       "legendFormat": "Max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Direct Buffers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(jvm_buffer_memory_used_bytes{application=\"$application\", instance=~\"$instance\", id=\"direct\"})",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "sum(jvm_buffer_total_capacity_bytes{application=\"$application\", instance=~\"$instance\", id=\"direct\"})",
       "legendFormat": "Capacity Bytes"
      }
     ]
    },
    {
     "title": "Direct Buffers Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(jvm_buffer_count_buffers{application=\"$application\", instance=~\"$instance\", id=\"direct\"})",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(jvm_buffer_memory_used_bytes{application=\"$application\", instance=~\"$instance\", id=\"mapped\"})",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "sum(jvm_buffer_total_capacity_bytes{application=\"$application\", instance=~\"$instance\", id=\"mapped\"})",
       "legendFormat": "Capacity Bytes"
      }
     ]
    },
    {
     "title": "Mapped Buffers Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(jvm_buffer_count_buffers{application=\"$application\", instance=~\"$instance\", id=\"mapped\"})",
       "legendFormat": "count"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Classloading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Classes Loaded",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(jvm_classes_loaded_classes{application=\"$application\", instance=~\"$instance\"})",
       "legendFormat": "Classes Loaded"
      }
     ]
    },
    {
     "title": "Classes Loaded Delta",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(delta(jvm_classes_loaded_classes{application=\"$application\",instance=\"$instance\"}[1m]))",
       "legendFormat": "Classes Loaded"
      }
     ]
    },
    {
     "title": "Classes Unloaded [1m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(jvm_classes_unloaded_classes_total{application=\"$application\", instance=~\"$instance\"}[1m]))",
       "legendFormat": "Classes Unloaded"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Count [1m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_count{application=\"$application\", instance=\"$instance\"}[1m])",
       "legendFormat": "{{action}} [{{cause}}]"
      }
     ]
    },
    {
     "title": "GC Stop duration [1m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_pause_seconds_sum{application=\"$application\", instance=\"$instance\"}[1m])) by (action,cause)/sum(rate(jvm_gc_pause_seconds_count{application=\"$application\", instance=\"$instance\"}[1m])) by (action,cause)",
       "legendFormat": "{{action}} [{{cause}}]"
      },
      {
       "expr": "sum(jvm_gc_pause_seconds_max{application=\"$application\", instance=\"$instance\"}) by (ation,cause)",
       "legendFormat": "max {{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Allocated/Promoted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_memory_allocated_bytes_total{application=\"$application\", instance=~\"$instance\"}[1m]))",
       "legendFormat": "allocated"
      },
      {
       "expr": "sum(rate(jvm_gc_memory_promoted_bytes_total{application=\"$application\", instance=\"$instance\"}[1m]))",
       "legendFormat": "promoted"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(jvm_threads_live_threads{application=\"$application\", instance=~\"$instance\"})",
       "legendFormat": "live"
      },
      {
       "expr": "sum(jvm_threads_daemon_threads{application=\"$application\", instance=~\"$instance\"})",
       "legendFormat": "daemon"
      },
      {
       "expr": "sum(jvm_threads_peak_threads{application=\"$application\", instance=~\"$instance\"})",
       "legendFormat": "peak"
      },
      {
       "expr": "sum(jvm_threads_started_threads_total{application=\"$application\", instance=~\"$instance\"})",
       "legendFormat": "started_total"
      }
     ]
    },
    {
     "title": "Thread States",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(jvm_threads_states_threads{application=\"$application\", instance=~\"$instance\"}) by (state)",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(disk_total_bytes{application=\"$application\", instance=~\"$instance\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(disk_free_bytes{application=\"$application\", instance=~\"$instance\"})",
       "legendFormat": "Free"
      }
     ]
    }
   ]
  },
  {
   "title": "Logback Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "INFO logs [30s]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(irate(logback_events_total{application=\"$application\", instance=~\"$instance\", level=\"info\"}[30s]))",
       "legendFormat": "info",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "ERROR logs [30s]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(irate(logback_events_total{application=\"$application\", instance=~\"$instance\", level=\"error\"}[30s]))",
       "legendFormat": "error",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "WARN logs [30s]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(irate(logback_events_total{application=\"$application\", instance=~\"$instance\", level=\"warn\"}[30s]))",
       "legendFormat": "warn",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "DEBUG logs [30s]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(irate(logback_events_total{application=\"$application\", instance=~\"$instance\", level=\"debug\"}[30s]))",
       "legendFormat": "debug",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "TRACE logs [30s]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(irate(logback_events_total{application=\"$application\", instance=~\"$instance\", level=\"trace\"}[30s]))",
       "legendFormat": "trace",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Executors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active threads",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(executor_active_threads{application=\"$application\", instance=~\"$instance\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Task queue",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
     "targets": [
      {
       "expr": "sum(executor_queued_tasks{application=\"$application\", instance=~\"$instance\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Queue slots available",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(executor_queue_remaining_tasks{application=\"$application\", instance=~\"$instance\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Thread pool",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(executor_pool_size_threads{application=\"$application\", instance=~\"$instance\"}) by (name)",
       "legendFormat": "actual threads [{{name}}]"
      },
      {
       "expr": "sum(executor_pool_max_threads{application=\"$application\", instance=~\"$instance\"}) by (name)",
       "legendFormat": "max threads [{{name}}]"
      }
     ]
    }
   ]
  }
 ]
}