name: AlertManager

on:
  schedule:
    - cron: '0 12 1 */1 *'
  push:
    branches: [ main ]
    paths:
      - alertmanager/**
  pull_request:
    branches: [ main ]
    paths:
      - alertmanager/**

jobs:
  test-alertmanager:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build --no-cache -f alertmanager/tests/Dockerfile -t alertmanager-test alertmanager