name: AlertManager

on:
  push:
    branches: [ main ]
    paths:
      - alertmanager/**
  pull_request:
    branches: [ main ]
    paths:
      - alertmanager/**

jobs:
  test-alertmanager:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build --no-cache -f alertmanager/tests/Dockerfile -t alertmanager-test alertmanager