name: Prometheus

on:
  push:
    branches: [ main ]
    paths:
      - prometheus/**
  pull_request:
    branches: [ main ]
    paths:
      - prometheus/**

jobs:
  test-prometheus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build --no-cache -f prometheus/tests/Dockerfile -t prometheus-test prometheus